### ISSUE TITLE
Adding 'Python Script Generator Using ChatGPT' 

### ISSUE THREAD

**Issue by ShayanTofique** [techyminati/python_codes#201]
I would like to propose adding a new project, the "Python Script Generator Using ChatGPT," to this repository. This project aims to provide a Python script that interacts with the OpenAI GPT-3 API to generate Python code snippets based on user-provided prompts. The generated Python scripts can be valuable for automating various tasks and simplifying the development process.

**Comment by techyminati** [comment]
sure

**Comment by ShayanTofique** [comment]
could you please review my PR, your feedback would be greatly appreciated.
